company_management_company:
    resource: "@CompanyManagementBundle/Resources/config/routing/company.yml"
    prefix:   /company

company_management_user:
    resource: "@CompanyManagementBundle/Resources/config/routing/user.yml"
    prefix:   /user

company_management_role:
    resource: "@CompanyManagementBundle/Resources/config/routing/role.yml"
    prefix:   /role

company_management_homepage:
    path:     /
    defaults: { _controller: CompanyManagementBundle:Default:index }
