acl_index:
    path:     /
    defaults: { _controller: "CompanyManagementBundle:Acl:index" }
    methods:  GET

acl_show:
    path:     /{id}/show
    defaults: { _controller: "CompanyManagementBundle:Acl:show" }
    methods:  GET

acl_new:
    path:     /new
    defaults: { _controller: "CompanyManagementBundle:Acl:new" }
    methods:  [GET, POST]

acl_edit:
    path:     /{id}/edit
    defaults: { _controller: "CompanyManagementBundle:Acl:edit" }
    methods:  [GET, POST]

acl_delete:
    path:     /{id}/delete
    defaults: { _controller: "CompanyManagementBundle:Acl:delete" }
    methods:  DELETE
