# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    regexp_generator:
        class: CompanyManagementBundle\Libraries\Regexp\RegexpGeneratorService

    regexp:
        class: CompanyManagementBundle\Libraries\Regexp\RegexpService
        arguments: ['@service_container']
